mysite/my_url_controller2/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django.urls import path, re_path

from my_url_controller2 import views

app_name = 'my_url_controller2'
urlpatterns = [
    path("reserve/", views.my_url_controller2_demo1, name="reverse"),
    re_path("(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]+)/$", views.my_url_controller2_demo2,
            name="my_url_controller2_demo2")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from rest_framework.documentation import include_docs_urls

from my_url_controller import views

urlpatterns = [
    path('docs/', include_docs_urls(title="站点页面标题")),
    path('admin/', admin.site.urls),
    path("", views.index),
    # re_path:简单的路由配置
    re_path("^my_url_controller/([0-9]{4})/([0-9]{2})/$", views.my_url_controller_demo1),
    # re_path:有名分组
    re_path("^my_url_controller/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]+)/$",
            views.my_url_controller_demo2),
    # include:分发 namespace:命名空间
    path("my_url_controller/", include("my_url_controller.urls", namespace="my_url_controller")),
    path("my_url_controller1/", include("my_url_controller.urls", namespace="my_url_controller1")),

    path("my_url_controller2/", include("my_url_controller2.urls", namespace="my_url_controller2")),
    path("my_model/", include("my_model.urls")),
    path("book_app/", include("book_app.urls")),
    path("books_app/", include("books_app.urls")),
    path("drf/", include("students.urls")),

]

mysite/templates/add_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add_Book</title>
    <link rel="stylesheet" href="/static/dist/css/bootstrap.css">
    <style>
        .container {
            margin-top: 100px;
        }
        .btn{
            margin-top: 10px;
        }
    </style>
</head>
<body>
<h3>添加书籍</h3>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="" method="post" >
            <div>
                <label for="">书籍名称</label>
                <input type="text" class="form-control" name="title">
            </div>
            <div>
                <label for="">价格</label>
                <input type="text" class="form-control" name="price">
            </div>
            <div>
                <label for="">出版日期</label>
                <input type="date" class="form-control" name="date">
            </div>
            <div>
                <label for="">出版社</label>
                <input type="text" class="form-control" name="publish">
            </div>
               <input type="submit" class="btn btn-success pull-right" >
                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        </form>

        </div>


    </div>
</div>
</body>
</html>

mysite/templates/add_books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加书籍</title>
    <link rel="stylesheet" href="/static/dist/css/bootstrap.css">
</head>
<body>
<h3>添加书籍</h3>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="" method="post">
                <div class="form-group">
                    <label>名称</label>
                    <input type="text" name="title" class="form-control" value="">
                </div>
                <div class="form-group">
                    <label>价格</label>
                    <input type="text" name="title" class="form-control" value="">
                </div>
                <div class="form-group">
                    <label>出版日期</label>
                    <input type="date" name="title" class="form-control" value="">
                </div>
                <div class="form-group">
                    <label>出版社</label>
                    <select name="publish_id" id="" class="form-control">
                        {% for publish in publish_list %}
                            <option value="{{ publish.pk }}">{{ publish.name }} </option>
                        {% endfor %}
                    </select>
                </div>
                 <div class="form-group">
                    <label>作者</label>
                    <select name="authors_id_list" id="" multiple class="form-control">
                        {% for author in author_list %}
                            <option value="{{ author.pk }}">{{ author.name }} </option>
                        {% endfor %}
                    </select>
                </div>
            <input type="submit" class="btn btn-success">

            </form>

        </div>
    </div>
</div>


</body>
</html>

mysite/templates/digit_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ajax</title>
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
</head>
<body>
<div>
    <h3>示例1 实现两个数值的计算 </h3>
    <input type="text" id="n1" value="">+
    <input type="text" id="n2" value="">=
    <input type="text" id="n3" value="">
    <button class="cal">计算</button>
</div>

<div>
    <h3>示例2 登录验证</h3>
    <form>
        用户名 <input type="text" id="user">
        密码 <input type="password" id="pwd">
        <input type="button" value="submit" class="login_btn"><span class="error"></span>
    </form>
</div>


</body>
<script>
    window.onload = function () {
        {# 示例1 实现两个数值的计算 #}
        $(".cal").click(
            function () {
                $.ajax({
                    url: '',
                    type: "post",
                    data: {
                        "n1": $("#n1").val(),
                        "n2": $("#n2").val(),
                    },
                    success: function (data) {
                        console.log(data);
                        $("#n3").val(data);
                    }
                })
            }
        );

        {# 示例2 登录验证   #}
        $(".login_btn").click(function () {
            $.ajax({
                url: "/books_app/login",
                type: "post",
                data: {
                    "user": $("#user").val(),
                    "pwd": $("#pwd").val(),
                },
                success: function (data) {
                    console.log(typeof data);
                    let user_data = JSON.parse(data);
                    console.log(typeof user_data );
                    if (user_data.user) {
                        location.href = "http://www.baidu.com"
                    } else {
                        $(".error").html(user_data .msg).css({"color": "red"})
                    }
                }
            })
        })

    }

</script>
</html>

mysite/templates/edit_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add_Book</title>
    <link rel="stylesheet" href="/static/dist/css/bootstrap.css">
    <style>
        .container {
            margin-top: 100px;
        }
        .btn{
            margin-top: 10px;
        }
    </style>
</head>
<body>
<h3>编辑书籍</h3>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="" method="post" >
            <div>
                <label for="">书籍名称</label>
                <input type="text" class="form-control" name="title" value="{{ book_object.title  }}">
            </div>
            <div>
                <label for="">价格</label>
                <input type="text" class="form-control" name="price" value="{{ book_object.price }}">
            </div>
            <div>
                <label for="">出版日期</label>
                <input type="date" class="form-control" name="date" value="{{ book_object.pub_date }}">
            </div>
            <div>
                <label for="">出版社</label>
                <input type="text" class="form-control" name="publish" value="{{ book_object.publish }}">
            </div>
               <input type="submit" class="btn btn-success pull-right" >
                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        </form>

        </div>


    </div>
</div>
</body>
</html>

mysite/templates/edit_books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑书籍</title>
    <link rel="stylesheet" href="/static/dist/css/bootstrap.css">
</head>
<body>
<h3>添加书籍</h3>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="" method="post">
                <div class="form-group">
                    <label>名称</label>
                    <input type="text" name="title" class="form-control" value="{{ edit_book_obj[0].title }}">
                </div>
                <div class="form-group">
                    <label>价格</label>
                    <input type="text" name="price" class="form-control" value="{{ edit_book_obj[0].price }}">
                </div>
                <div class="form-group">
                    <label>出版日期</label>
                    <input type="date" name="publish_date" class="form-control" value="{{ edit_book_obj[0].pub_date}}">
                </div>
                <div class="form-group">
                    <label>出版社</label>
                    <select name="publish_id" id="" class="form-control">
                         {% for publish in publish_list %}
                            {% if edit_book_obj.publish == publish %}
                                <option selected value="{{ publish.pk }}">{{ publish.name }}</option>
                            {% else %}
                                <option value="{{ publish.pk }}">{{ publish.name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
                 <div class="form-group">
                    <label>作者</label>
                    <select name="authors_id_list" id="" multiple class="form-control">
                    {% for author in author_list %}



                     {% endfor %}
                    </select>
                </div>
                <input type="submit" class="btn btn-success">
                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">

            </form>

        </div>
    </div>
</div>


</body>
</html>

mysite/templates/file_put.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ajax</title>
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
</head>
<body>
<div>
    <h3>示例1:基于form表单的文件上传:multipart/form-data</h3>
    <form action="" method="post" enctype="multipart/form-data">
        <label for="user">用户名</label>
        <input type="text" name="user">
        <label for="avatar">头像</label>
        <input type="file" name="avatar">
        <input type="submit">
    </form>
</div>

<div>
    <h3>示例2:基于form表单的文件上传:application/x-www-form-urlencoded</h3>
    <form action="" method="post">
        <label for="user2">用户名</label>
        <input type="text" name="user2" id="user2">
        <label for="avatar2">头像</label>
        <input type="file" name="avatar2" id="avatar2">
        <input type="button" class="btn" value="提交">
    </form>
</div>

<div>
    <h3>示例3: application/json</h3>
    <label for="user3">用户名3</label>
    <input type="text" name="user3" id="user3">
    <input type="button" class="btn3" value="提交">
</div>

</body>
<script>
    window.onload = function () {
        $(".btn").click(function () {
            let formData = new FormData();
            formData.append("user", $('#user2').val());
            formData.append("avatar", $('#avatar2')[0].files[0]);
            $.ajax({
                url: "",
                type: "post",
                contentType: "",
                processData: false,
                data: formData,
                success: function (data) {
                    console.log(data)
                }
            })
        });


        $(".btn3").click(function () {
            $.ajax({
                url: "",
                type: "post",
                contentType: "application/json",
                data: JSON.stringify({
                    "user": $('#user3').val()
                }),
                success: function (data) {
                    console.log(data)
                }
            })
        })
    }
</script>
</html>

mysite/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
</head>
<body>
<h4>当前时间:{{ now_time }}</h4>
{% if username  %}
    <h3>Hi,{{ username }}</h3>
    <p>上次登陆时间:{{ last_visit_time }}</p>
    <a href="/logout/">注销</a>
{% endif %}
</body>
</html>

mysite/templates/my_template_base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="style.css" />
    <title>{% block title %} My amazing site {% endblock title %}</title>
</head>

<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/blog/">Blog</a></li>
        </ul>
        {% endblock sidebar %}
    </div>

    <div id="content">
        {% block content %}{% endblock content %}
    </div>
</body>
</html>

mysite/templates/my_template_include.html
````````````````````````````<br>
{% include 'my_template_base1.html' %}
    Body

````````````````````````````<br>

mysite/templates/my_template_inherit.html
{% extends "my_template_base1.html" %}
super调用:
{% block title %}
    {{ super() }}
    aaa
{% endblock %}
基础调用:
{% block sidebar %} bbb {% endblock %}

mysite/templates/my_url_controller2_demo2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>my_url_controller2_demo2</title>
</head>
<body>
<a href="{% url 'my_url_controller2:my_url_controller2_demo2' year="2012" month="02" day="01" %}">2012 Archive</a>


</body>
</html>

mysite/templates/paginator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>paginator</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<ul>
    {% for book in current_page %}
        <li>{{ book.title }}:{{ book.price }}</li>
    {% endfor %}
</ul>


{#分页器#}
<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if current_page.has_previous() %}
            <li>
                <a href="?page={{ current_page.previous_page_number() }}" aria-label="Previous">
                    <span aria-hidden="true">上一页</span>
                </a>
            </li>
        {% else %}
            <li class="disabled"><a href="" aria-label="Previous"><span aria-hidden="true">上一页</span></a></li>
        {% endif %}


        {% for item in page_range %}
            {% if current_page_num == item %}
                <li class="active"><a href="?page={{ item }}">{{ item }}</a></li>
            {% else %}
                <li><a href="?page={{ item }}">{{ item }}</a></li>
            {% endif %}
        {% endfor %}


        {% if current_page.has_next() %}
            <li>
                <a href="?page={{ current_page.next_page_number() }}" aria-label="Next"><span
                        aria-hidden="true">下一页</span></a>
            </li>
        {% else %}
            <li class="disabled"><a href="" aria-label="Next"><span aria-hidden="true">下一页</span></a></li>
        {% endif %}

    </ul>
</nav>
</body>
</html>

mysite/templates/view_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ViewBook</title>
    <link rel="stylesheet" href="/static/dist/css/bootstrap.css">
</head>
<body>
<h3>查看书籍</h3>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <a  href="/book_app/add/" class="btn btn-success"  >添加</a>
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>书籍名称</th>
                    <th>价格</th>
                    <th>出版日期</th>
                    <th>出版社</th>
                    <th>删除操作</th>
                    <th>编辑操作</th>
                </tr>
                </thead>
                {% for book in book_list %}
                <tr>
                    <td> {{ book.title }}</td>
                    <td> {{ book.price }}</td>
                    <td> {{ book.pub_date }}</td>
                    <td> {{ book.publish }}</td>
                    <td><a href="/book_app/delete/{{ book.pk }}" class="btn btn-danger" >删除</a></td>
                    <td><a href="/book_app/edit/{{ book.pk }}" class="btn btn-info">编辑</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
<table>

</table>
</body>
</html>

mysite/templates/view_books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查看书籍</title>
    <link rel="stylesheet" href="/static/dist/css/bootstrap.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <table class="table table-bordered table-hover table-striped">
                <thead>
                <tr>
                    <th>编号</th>
                    <th>书籍名称</th>
                    <th>价格</th>
                    <th>出版日期</th>
                    <th>出版社</th>
                    <th>作者</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for book  in book_list %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td>{{ book.title }}</td>
                    <td>{{ book.price }}</td>
                    <td>{{ book.pub_date }}</td>
                    <td>{{ book.publish__name }}</td>
                    <td>{{ book.authors__name }}</td>
                    <td>
                        <a href="/books_app/{{ book.id }}/{{ book.authors__name }}/change" class="btn btn-warning">编辑</a>
                        <a href="/books_app/{{ book.id }}/delete" class="btn btn-danger">删除</a>
                    </td>
                </tr>

                {% endfor %}


                </tbody>

            </table>
        </div>
    </div>
</div>

</body>
</html>